version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # On s'arrête à l'étape 'deps' du Dockerfile, qui installe juste les dépendances.
      # On ne veut pas 'build' ou 'run' en production pour le développement.
      target: deps
    ports:
      - "3000:3000"
    # On monte le code local dans le conteneur pour avoir le hot-reload
    volumes:
      - .:/app
      # On s'assure que les node_modules du conteneur ne sont pas écrasés par un dossier local
      - /app/node_modules
      - /app/.next
    # On force la commande de développement
    command: pnpm dev
    environment:
      # Nécessaire pour que Next.js détecte les changements de fichiers dans Docker
      - WATCHPACK_POLLING=true
    restart: unless-stopped

  # --- SERVICE MINIO ---
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # Port de l'API S3
      - "9001:9001" # Port de la Console d'administration Web
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin_password"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: